# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-13 11:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanetDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planet_name', models.CharField(max_length=100)),
                ('size_planet', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=20)),
                ('color_planet', models.CharField(max_length=20)),
                ('population', models.IntegerField(max_length=100)),
                ('planet_position', models.IntegerField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='SystemDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_system', models.CharField(max_length=100)),
                ('how_many_planets', models.IntegerField(max_length=3)),
                ('color_star', models.CharField(max_length=100)),
                ('pos_x', models.IntegerField(max_length=10)),
                ('pos_y', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='planetdb',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipdisplay.SystemDB'),
        ),
    ]
