# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipdisplay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrewDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_in_crew', models.CharField(choices=[('C', 'Captan'), ('M', 'Mechanik'), ('P', 'Pilot')], max_length=20)),
                ('position', models.CharField(max_length=20, null=True)),
                ('number', models.IntegerField(max_length=3)),
            ],
        ),
    ]
