# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 16:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shipdisplay', '0002_crewdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='crewdb',
            name='name',
            field=models.CharField(default=datetime.datetime(2016, 6, 2, 16, 48, 21, 885000, tzinfo=utc), max_length=30),
            preserve_default=False,
        ),
    ]
